### ISSUE TITLE
Proposition to Change Method of Signature Veritifcation

### ISSUE THREAD

**Issue by 1oAn7TNT** [opnsense/changelog#3]
## Issue
With any security focused project, there is focus on making sure that the software that is produced reaches the user without any modifications. (eg. reproducible builds, checksums, etc.)

The method you have implemented for verification of ISO's and the checksums is archaic, and I am not able to find any documentation on how to get it to work. 

I propose that you switch over to a safer, and more standard way of checksum and signature verification (using GPG).

## Proposed Steps
1. Create a revocation certificate. This will let you let you remove the key from any keyserver if it is compromised.
2. Upload your public key to a keyserver (ideally more than 1) such as pgp.mit.edu, or keys.gnupg.net. You can also host your own key on your website.
3. Create a single file of all the SHA256 checksums of the ISOs avaible for download.
4. **Sign this file using GPG.** 
5. Put the ISOs, the public key, and signed checksums file aviable and that is it.

## Further reading / information
A guide to exporting your GPG key for keyservers
- https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Step_by_Step_Guide/s1-gnupg-export.html

Scroll down and you can see how other security projects handle signature verification. Emulating what they do is most likely safer than the model that is being used now.
- https://docs.kali.org/introduction/download-official-kali-linux-images/

**Comment by fichtner** [comment]
I strongly suggest you change „archaic“ to what we actually do use for verfification and go on a treasure hunt for where we describe the process (spoiler alert: it‘s in every image release announcement).

Then point out the flaws and why GPG is supposed to any better.

From my POV, GPG can also be considered „archaic“. 😉


Cheers,
Franco

**Comment by 1oAn7TNT** [comment]
Apologies if it sounded a bit condescending.
There are a few things I think that should be addressed. 

1. Ease of use / Standardization for User
2. Fail safes in case your website and/or GitHub get hacked

### Issue 1

Now part of this may sound rude, but do bear with me. The methodology used to verify software checksums and ISOs is largely a standard procedure. Usually, it is import the key, verify against signed signatures/checksums, and then check the ISOs themselves. 

I don't understand why OPNSense opts for something else (please do explain, as I am curious), or understand the commands itself. This whole issue came with me trying to verify the ISOs and I was not able to using the two commands you provided. **Adding a brief tutorial on using your method of verification and how it is supposed to work** is a great step regardless if you are changing what you are doing or not. (If I get it to work, I'll write it for you as well also!).

#### More Information

When I used archaic I was specifically referring to this command
> `openssl base64 -d -in image.bz2.sig -out /tmp/image.sig`

Which, if I understand correctly, means to use `openssl` and `base64` to decode the signature/checksum file into this:

`z@devbox:~/Downloads$ cat OPNsense-18.7-OpenSSL-nano-amd64.img.bz2.sig 
cb0272f0bd945ea8070d9a40af2cd47a3b68e9bd389395b285bb9ab4128d1f00`

`z@devbox:~/Downloads$ openssl base64 -d -in OPNsense-18.7-OpenSSL-nano-amd64.img.bz2.sig 
q�6�g�m�x���ӽ��4i��w��ݾ�{����w����������o��4z@devbox:~/Downloads$ 
`

Commands like that, without any linked document explaining why they are needed or used makes me confused. It may be my own lack of skill with the `openssl` tool, but I hope you understand the merit of what I mean. 

I did try verifying using your commands, and I got a Verification Failed response. It may be due to my errors, a lack of clear instructions, or something on your end. (Note: I did this on 2 machines, using 3 different internet connections)

### Issue 2

This one is more of a general piece, but having your public keys in a few places is good security practice. Like the backup adage: one is none, two is one. If the only places where one can get your security key is on your website and/or GitHub (which may be linked), a hypothetical attacker may be able to change both. Sure there are safeguards to this, but a publicly available keyserver can mitigate that.

**Comment by 1oAn7TNT** [comment]
Ignore my comments about the Verification Failed, and the archaic-ness. I figured out how to verify it, but it required me to find stuff that was not on this GitHub page or your "Fast Download Selection." 

I do heavily encourage your team to add a FAQ on how to verify a download. If you want I can write it.

**Comment by arrogant2** [comment]
I second this issue. The "treasure hunt" you describe to find the instructions was not helpful. I am looking at [this](https://github.com/opnsense/changelog/blob/master/doc/18.7/18.7) page.

The instructions are difficult to follow, and do not follow industry standard practice for file integrity checking and verification. I did eventually figure out how to do it:

1. Go to the download page on opnsense.org.
2. Right click the download button and click open in new tab.
3. Remove the file name at the end of the URL.
4. A list of files will be displayed, which provides the necessary sig files for verification.

This requires digging to find, and is extremely difficult for the end user. None of this is documented very well in a logical location, (i.e. on the download page), and using openssl for verifying images is a bad practice. There are two reasons for this:

1. It is a non standard way to verify files that most people do not understand.
2. It is less secure than GPG.

> Then point out the flaws and why GPG is supposed to any better.

I am sure openssl is a perfectly viable way to verify file integrity, but the way you distribute the public key is not ideal. The point of GPG is so that you can have a key (preferably verified through chain of trust, although this almost never happens) against which you can verify all releases. Distributing a key per-release (as you seem to be doing), opens the project up to potential attacks where people hack the infrastructure and fake releases, or modify existing ones. Having a long lasting, single key that can be verified against is essential. @0ss point about revocation certificates is also a good one, as I am not sure if this can be done with openssl.

Up through 17.7, you didn't seem to be doing verification at all. At least, there is no pubkey in that release announcement. While I suppose openssl is better than nothing at all, it is still not the best tool to use for this problem.

Security issues aside, it is a nonstandard way of doing this. Even if it weren't extremely poorly documented (which it is), every other serious security project that does OS releases does it this way. See: Kali, Qubes, Whonix, even Ubuntu. This also includes non-OS projects like Tor Browser. This is the way everyone does it, and reinventing the wheel while making security objectively worse seems counterproductive to me. If nothing else, GPG should be used because it is the industry standard.

For the reasons stated above, GPG is not "archaic", and for this particular purpose is a better verification technique than openssl.

I would recommend reading the links that @0ss posted above, especially the Kali one. That, in my opinion, is how verification _should_ be handled.

As an aside: I know that there are a lot of sock puppet accounts being used by the PfSense people to try and defame the project. I assure you that is not my intention. I normally do not use github, but this issue irritated me enough to make an account.

**Comment by fichtner** [comment]
We generate a new key for each major release, twice a year. Revocation is not necessary.

Docs here could always use more help, see https://docs.opnsense.org/manual/install.html where that info would be located and for the source https://github.com/opnsense/docs


Cheers,
Franco

**Comment by arrogant2** [comment]
I agree that the docs need to be updated with better instructions. Ideally, verification instructions would be on the download page as well.

> We generate a new key for each major release, twice a year. Revocation is not necessary.

What if the project is compromised? I.e. someone hacks your forums, mailing lists, github, website, etc. Again, that is the point of having a long lasting, single key against which everything can be verified. If you download a GPG key two years earlier and use it to verify the image, it is highly unlikely that the project has been compromised since before you downloaded it. With that long, someone would have noticed it.

Again, even if you disagree about the security side of it, it is a standard practice. This is how everyone else does it. In addition, as a rule I trust projects more when they use a commonly understood, industry standard practice to verify their releases.

**Comment by fichtner** [comment]
Regarding issue 2 we do have a couple of primary sources off the top of my head:

* https://pkg.opnsense.org/releases/mirror/README
* https://forum.opnsense.org/index.php?topic=9280.0
* https://opnsense.org/opnsense-18-7-released/
* (this repository)
* https://lists.opnsense.org/pipermail/announce/2018-July/000117.html (also available via mail so your 
HTTP(S) is not intercepted)
* https://pkg.opnsense.org/FreeBSD:11:amd64/18.7/sets/changelog.txz (lands signed and verified in the GUI of the running software)

I just want to point out that I appreciate this discussion, but it has not been researched very well, which, most likely, stems from a lack of documentation, which we can easily change. :)


Cheers,
Franco

**Comment by arrogant2** [comment]
> I appreciate this discussion, but it has not been researched very well

I would disagree. Both I and @0ss have provided links to the resources we are referencing, as well as a comprehensive analysis of our opinions on it. We are providing our opinions of what we have observed to be a secure, industry standard practice that OPNSense as a project has not implemented.

> Regarding issue 2 we do have a couple of primary sources off the top of my head.

This is an improvement. These primary sources should be documented on the download page, as well as any others you can think of. In addition, they should be listed in the release announcements from all sources. This would help alleviate some of my concerns.

IMHO, while this is still worse than GPG, it is good enough. I would urge you to reconsider how you do release verification, but failing that, this will suffice.

**Comment by fichtner** [comment]
> I would disagree.

You may. So I want to make myself more clear: not very well researched in the scope of OPNsense.

> This is an improvement.

It's not. It was a missed precondition which describes my point in more detail, see above.

Can you tell me what particular attack you are worried about?


Cheers,
Franco

**Comment by mimugmail** [comment]
Why do you so often mention industry standard?

Cisco, biggest player in the world only offers SHA sums:
https://software.cisco.com/download/home/286283326/type/280775065/release/9.9.2%20Interim

Mellanox offers for their switching systems only MD5SUM

Juniper, for their SRX security plattforms also only SHA:
https://support.juniper.net/support/downloads/

I'm quite sure Fortigate, Checkpoint and Sophos too ... 

This is industry standard, not the linux iso thing. 
You are totally right that a signing for the checksums is very important, but don't call it industry standard .. it's not. In the industry you sadly have to trust the vendor.

**Comment by fabianfrz** [comment]
I have to add my opinion here as well:

OpenSSL is a good tool to verify signatures as it it its main job for which it has been built (using it for SSL and TLS - ok, the first one would be good if nobody supports it anymore…) where it is very important to ensure the integrity of the connection as well as confidentiality (=> encryption), authentication and authorization (both are based on PKIs which are data structures which are also using public key cryptography).

OpenSSL supports many cryptographic standards so it also supports for example PKCS#7, which is used to sign emails as well which works with standard X.501 certificates which effectively means, that everyone with a standard certificate bundle can verify the file. In detached mode, you can even provide it as a separate file. This already gives a huge advantage over GPG: You already have a root for the chain of trust in your system (your CA bundle) because the only secure way to trust a public key is by comparing the fingerprint with the with the one of the key owner on a cryptoparty or privately (or by using another chain of trust).

The raw signatures may not be optimal to verify but gpg is not the solution because if an attacker can change the files on the server, he can also change the id of the GPG key.

**Comment by arrogant2** [comment]
> You are totally right that a signing for the checksums is very important, but don't call it industry standard .. it's not. In the industry you sadly have to trust the vendor.

@mimugmail That is technically correct. "Industry standard" may be misleading in this sense. What I meant was, every other _open source_ project that is similar to this implements a GPG verification method. Obviously, proprietary products that companies sell are more representative of the "industry". However, their security practices are evidently terrible, and furthermore, because they are not open source (at least in the cases of Cisco and--I believe--Juniper), they cannot be trusted for actual security. So, they can't really be used for a basis of comparison because they suck anyway. Even that being said, I am surprised. Mellanox is particularly bad; MD5 has been deprecated for years, and it only takes a day or two on even mediocre hardware to generate collisions.

@fichtner I think we generally agree. Arguing those points would be pedantic on my part, so I won't. To summarize, we need to fix 3 things:

1. Add a copy of the verification instructions to the download page.
2. Explain where to get the sig files, the ISOs, and the shasums. The release announcement is poorly worded, and poorly organized. This information should be at the top, and it should be very explicit in explaining where to get each of the files needed for verification. I will make a pull request later to fix this.
3. Add the list of primary sources to the release announcement and the download page, that way people know where to look so that they can verify that the pubkey and the shasums match what has been posted on all of them.

> Can you tell me what particular attack you are worried about?

One specific one has to do with the short lifespan and per-release nature of your pubkey. This is an issue regardless of whether you use openssl or GPG, because when a new key is used for every release, it is impossible to tell if it was legitimately you that posted the new key, or an attacker. It completely negates one of the big reasons for having the pubkey in the first place: a long lasting identifier that can be downloaded once, and can be used to verify all subsequent messages/files posted regardless of whether an attacker has compromised the infrastructure. Granted, this only applies provided that the key itself hasn't been compromised, but this is unlikely provided it is not stored on public facing infrastructure. Even if it is, that is _exactly_ the reason why revocation certificates are important.

It may seem like a far fetched idea, but you cannot rule out the possibility of an attacker compromising your infrastructure. Remember Copperhead OS? That was a good example of a hostile takeover, where a malicious party had access to the infrastructure. Luckily, Daniel Micay (the dev) destroyed the private keys for signing updates, and it was impossible to use his GPG key to sign new releases pushed by the malicious party (his onetime business partner). If they had been using your "key per release" model, his partner could have just released a new key for his new (malicious) release, and nobody would have been the wiser. _This_ is one of the attacks I am worried about.

@fabianfrz My main argument for GPG is based on it being the thing everyone else uses, the "industry" standard (I am well aware that using this term is not _technically_ correct; please bear with me). As I stated above, most of the open source OS projects (security and non-security related) use GPG. _This is the main argument, any technical or security differences between GPG and openssl are secondary._ It is about making it easier for the end user, by using the method they are _already familiar with._

That being said, I will also attempt to address your argument in favor of openssl, _bearing in mind that it isn't the main issue._

> OpenSSL supports many cryptographic standards so it also supports for example PKCS#7, which is used to sign emails as well which works with standard X.501 certificates which effectively means, that everyone with a standard certificate bundle can verify the file. [...] This already gives a huge advantage over GPG: You already have a root for the chain of trust in your system (your CA bundle) because the only secure way to trust a public key is by comparing the fingerprint with the with the one of the key owner on a cryptoparty or privately (or by using another chain of trust).

Ok, let me ask you this: can the OPNSense release key be verified against the standard OS certificate bundle? If so, great! Add it to the documentation so people can do it. If not, why bother talking about it?

I am aware of the limitations of GPG. It is highly unlikely that anyone would _actually_ verify against the owner's fingerprint. If openssl pubkeys can be verified against the certificate bundle, then it does have a potential advantage, but consider that root CAs can be compromised. Unless you are running your own certificate authority that is _trusted by the OS via the cert bundle,_ then this is off the table. If you are, it isn't being used by the website; opnsense.org uses Let's Encrypt.

> The raw signatures may not be optimal to verify but gpg is not the solution because if an attacker can change the files on the server, he can also change the id of the GPG key.

This is exactly why you need a single, long lasting GPG key with a revocation certificate. If you have a key that you downloaded several months ago (or better yet verified), then the attacker cannot modify your local copy, and you can tell if the public one has been modified because you have the original. Again, when you use one key per release it is impossible to do this, because the key changes per release, invalidating your old (trusted) one.

Bearing all of this in mind: assuming you used a single key instead of per release, and it could be verified against the cert bundle, _and_ you run your own CA (not Let's Encrypt), then using openssl over GPG makes sense at a technical level. Even if this were the case, I would argue for GPG solely on the basis of standardization.

**Comment by mimugmail** [comment]
@arrogant2 A pull request against the docs with a detailed expl. would be cool, then every announcement can just link to official docs. I'd really appreciate your contribution to this project as time is limited for all of us 👍

**Comment by arrogant2** [comment]
I have added the instructions to the wiki with the above pull request. I still consider the situation non-ideal, but at least it isn't frustrating for lack of documentation. If you insist on using openssl, I recommend simply distributing the base64 version of the sig file, and eliminate the extra step where the file is created in /tmp.

I still advocate the use of GPG for the reasons stated above. If anyone else reading this agrees with me, I recommend they chime in as well.

**Comment by fichtner** [comment]
Merged. Future release announcements and README files will link to the document.
